### ISSUE TITLE
The Read/Show instances for TimeZone are misleading

### ISSUE THREAD

**Issue by neongreen** [haskell/time#28] opened 2015-03-17 00:25 UTC
It isn't said anywhere that `read`ing a `TimeZone` is useless (since it only reads the name, leaving `timeZoneMinutes` empty).

Should the `Read` instance for `TimeZone` be removed? If not, then at least this behaviour should be documented and warned about.

**Comment by AshleyYakeley** [comment] 2015-05-31 04:19
Can you reproduce this? It should recognise any time zone in the `knownTimeZones` field of the `TimeLocale` you are passing in.

**Comment by AshleyYakeley** [comment] 2015-05-31 04:21
Hmm, for `read`, where you don't pass in a `TimeLocale`, it should recognise the time-zones in `defaultTimeLocale`.

**Comment by AshleyYakeley** [comment] 2015-08-23 20:04
Closing this as not reproducible.

**Comment by l29ah** [comment] 2018-11-23 13:19
```
λ> getZonedTime
2018-11-23 16:14:00.94267804 MSK
λ> ct <- getZonedTime
λ> timeZoneMinutes $ zonedTimeZone ct
180
λ> timeZoneMinutes $ zonedTimeZone $ read "2018-11-23 16:14:00.94267804 MSK"
0
```
This sucks, since x ≠ read $ show x.
How do i read ZonedTime correctly?

**Comment by l29ah** [comment] 2018-11-23 13:19
```
λ> read "2018-11-23 02:43:56.725423116 MSK" :: ZonedTime
2018-11-23 02:43:56.725423116 MSK
λ> zonedTimeToUTC $ read "2018-11-23 02:43:56.725423116 MSK"
2018-11-23 02:43:56.725423116 UTC
```

**Comment by AshleyYakeley** [comment] 2019-03-15 09:33
OK, added documentation about this.

**Closed by AshleyYakeley** 2019-03-15 09:33 UTC
